name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        dockerfile: docker/Dockerfile

    - name: Build Docker Image
      run: docker build -t my-docker-image -f docker/Dockerfile .
      working-directory: ${{ github.workspace }}

    - name: Run Docker Container
      run: docker run -d my-docker-image
      # Add environment variables and port bindings as needed.

    # Add steps for testing or artifact generation within the Docker container if required.

    - name: Show Docker Image
      run: docker images

    - name: Show Running Containers
      run: docker ps -a

    # Optionally, stop and remove containers after testing.
    - name: Stop Docker Container
      run: docker stop $(docker ps -q --filter "ancestor=my-docker-image") || true

    - name: Remove Docker Container
      run: docker rm $(docker ps -a -q --filter "ancestor=my-docker-image") || true
