name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v2
      with:
        dockerfile: docker/Dockerfile

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    - name: Run Docker Container
      run: docker run my-docker-image

    # Add additional steps here, such as running tests inside the Docker container.

    - name: Show Docker Image
      run: docker images

    - name: Show Running Containers
      run: docker ps -a

    # Add more steps as needed for your CI/CD pipeline.
