name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        dockerfile: docker/Dockerfile

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    - name: Run Docker Container
      run: |
        output=$(docker run my-docker-image)
        echo "$output"  # This will display the output in the GitHub Actions logs
        echo "::set-output name=output::$output"  # This will set the output as a workflow output

    - name: Show Docker Image
      run: docker images

    - name: Show Running Containers
      run: docker ps -a

    - name: Use Docker Output
      run: |
        docker_output="${{ steps.docker.outputs.output }}"
        echo "Docker Output: $docker_output"  # Display the captured output
        # You can use 'docker_output' as needed in your workflow
